In [2]:
import numpy as np

arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Broadcast

In [9]:
arr[:4]=99
arr

array([99, 99, 99, 99, 11, 11, 11,  7,  8,  9, 10])

In [10]:
arr= np.arange(0,11)
sliceofarr= arr[:7] # this is reference, not copy meaning that changes in slice will affect the main arr
sliceofarr

array([0, 1, 2, 3, 4, 5, 6])

We have made the changes in slice but the change is directly broadcasted to main arr

In [11]:
sliceofarr[:]= 11
arr

array([11, 11, 11, 11, 11, 11, 11,  7,  8,  9, 10])

This will create a copy

In [12]:
sliceofarr= arr[:7].copy()
sliceofarr

array([11, 11, 11, 11, 11, 11, 11])

## Indexing and selection

In [14]:
arr= np.array([[5,10, 15],
             [20, 25,40],
             [43,53,23]])
arr

array([[ 5, 10, 15],
       [20, 25, 40],
       [43, 53, 23]])

In [17]:
arr[1][2], arr[1,2]  # same as double bracket

(40, 40)

### Slice notation

In [20]:
arr[:2,:3] # row= 0,1, column= 0,1,2

array([[ 5, 10, 15],
       [20, 25, 40]])

### Conditional selection

In [24]:
arr[arr>10]

array([15, 20, 25, 40, 43, 53, 23])

In [26]:
arr= np.arange(50).reshape(5,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [27]:
arr[1:3,4:6]

array([[14, 15],
       [24, 25]])

## Numpy operations

In [28]:
arr= np.arange(10)

In [29]:
arr/arr # numpy will not give zero division error

C:\Users\user\AppData\Local\Temp\ipykernel_4284\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [35]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([1,2,3,4])

arr1+arr2

array([[2, 4, 6, 8],
       [2, 4, 6, 8]])

In [36]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])

arr1+arr2

ValueError: operands could not be broadcast together with shapes (2,4) (4,4) 

In [56]:
arr1=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
arr2=np.array([[1,2,3,4]])

arr3= arr1+arr2
arr3

array([[2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8]])

In [53]:
arr.sum()

45

Get some of all the columns in matrix

In [57]:
arr3.sum(axis=0)

array([ 6, 12, 18, 24])

#### Identity matrix

In [41]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Generate rand num

In [43]:
np.random.rand(1)

array([0.01801296])

#### Random number b/w 0 and 1 

In [44]:
np.random.rand(25)

array([0.59480001, 0.39586681, 0.28837638, 0.96497041, 0.4742482 ,
       0.6626502 , 0.21507451, 0.61218827, 0.24272052, 0.51664462,
       0.72560419, 0.50018982, 0.66859384, 0.10347429, 0.98691523,
       0.48410394, 0.68980048, 0.31806072, 0.82888582, 0.27109716,
       0.69112393, 0.73739635, 0.62376706, 0.22283906, 0.06202441])

In [50]:
np.random.randint(0,25, size=(5,5))

array([[ 8, 17, 10,  3, 20],
       [24,  9, 19,  5, 21],
       [21,  8, 11, 22,  7],
       [23, 12, 11, 14, 16],
       [ 9, 13, 17, 20,  2]])

In [51]:
np.linspace(1,10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [52]:
np.linspace(1,10, 100).reshape(10,10)

array([[ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
         1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182],
       [ 1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
         2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273],
       [ 2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
         3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364],
       [ 3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
         4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455],
       [ 4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
         5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545],
       [ 5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
         6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636],
       [ 6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
         6.90909091,  7.        ,  7.09090909